artifact_uri: file:///home/mle-user/mle_projects/mle-mlflow/mlflow_experiments_store/0/981fa90a842545b18d2fd25e972a4026/artifacts
end_time: 1750962749986
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 981fa90a842545b18d2fd25e972a4026
run_name: Default
run_uuid: 981fa90a842545b18d2fd25e972a4026
source_name: ''
source_type: 4
source_version: ''
start_time: 1750962749971
status: 3
tags: []
user_id: mle-user
